# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            All Things Dork
tagline:          Ramblings of a black nerd
description:      Ramblings of a black nerd
url:              http://www.allthingsdork.com

author:
  name:           Jeff Smith
  url:            https://twitter.com/DarkAndNerdy

paginate:         20

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bobbidigital/allthingsdork
